version: "3.8"

services:
  minio:
    container_name: minio_anytype
    hostname: minio_anytype
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    ports: 
      - 9000:9000
      - 9001:9001
    volumes:
      - /path/to/anytype-data/s3:/data
    restart: unless-stopped
    env_file:
      - .env.example
  mongodb:
    container_name: mongodb_anytype
    image: mongo:4.4
    volumes:
      - /path/to/anytype-data/db:/data/db
    restart: unless-stopped
    env_file:
      - .env.example
  redis:
    container_name: redis_anytype
    image: redis

  any-node:
    container_name: node_anytype
    image: any-docker:0.33.3
    restart: unless-stopped
