version: "3.8"

services:

  minio:
    container_name: minio_anytype
    hostname: minio_anytype
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    ports: 
      - 9000:9000
      - 9001:9001
    volumes:
      - s3:/data
    restart: unless-stopped
    env_file:
      - .env.example
      
  mongo:
    container_name: mongo_anytype
    image: mongo:4.4
    volumes:
      - db:/data/db
    restart: unless-stopped
    env_file:
      - .env.example
      
  redis:
    container_name: redis_anytype
    image: redis
    
  any-node:
    container_name: node_anytype
    image: docker.io/sambouwer/any-sync-docker:0.33.3
    restart: unless-stopped

volumes:
  s3:
  db:
