name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  #Dockerfile vars
  REPO: sambouwer
  GOLANG_VER: 1.19.11
  ANYTYPE_VER: 0.33.3
  ANY_DOCKER_VER: 1
  
  #vars
  IMAGENAME_COORDINATOR: any-sync-coordinator
  IMAGENAME_NODE: any-sync-node
  IMAGENAME_FILENODE: any-sync-filenode
  
  IMAGEFULLNAME_COORDINATOR: $REPO/$IMAGENAME_COORDINATOR:$ANYTYPE_VER-$ANY_DOCKER_VER
  IMAGEFULLNAME_NODE: $REPO/$IMAGENAME_NODE:$ANYTYPE_VER-$ANY_DOCKER_VER
  IMAGEFULLNAME_FILENODE: $REPO/$IMAGENAME_FILENODE:$ANYTYPE_VER-$ANY_DOCKER_VER
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Build docker image
        run: docker build --file any-node/Dockerfile --pull --build-arg GOLANG_VER=$GOLANG_VER -t $IMAGEFULLNAME_COORDINATOR --target $IMAGENAME_COORDINATOR .
      
