name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:  
  IMAGEFULLNAME_COORDINATOR: "$REPO/$IMAGENAME_COORDINATOR:$ANYTYPE_VER-$ANY_DOCKER_VER"
  IMAGEFULLNAME_NODE: "$REPO/$IMAGENAME_NODE:$ANYTYPE_VER-$ANY_DOCKER_VER"
  IMAGEFULLNAME_FILENODE: "$REPO/$IMAGENAME_FILENODE:$ANYTYPE_VER-$ANY_DOCKER_VER"
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Build docker image
        run: docker build --file any-node/Dockerfile --pull --build-arg GOLANG_VER=${{ env.GOLANG_VER }} -t ${{ env.IMAGEFULLNAME_COORDINATOR }} --target ${{ env.IMAGENAME_COORDINATOR }} .
      
