name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Build docker image
        run: docker build --file any-node/Dockerfile --pull --build-arg GOLANG_VER=${{ GOLANG_VER }} -t ${{ IMAGEFULLNAME_COORDINATOR }}--target ${{ IMAGENAME_COORDINATOR }} .
      
